### ISSUE TITLE
Crash on master when inheriting from unknown methodmap

### ISSUE THREAD

**Issue by Fyren** [alliedmodders/sourcepawn#1000]
`methodmap A < B {}` should error that B doesn't exist, but instead crashes:

```
#0  sp::cc::Stmt::kind (this=0x0) at sourcepawn/compiler/parse-node.h:132
#1  0x5663ef1f in sp::cc::MethodmapDecl::is_a (node=0x0)
    at sourcepawn/compiler/parse-node.h:1878
#2  0x56637a64 in sp::cc::Stmt::as<sp::cc::MethodmapDecl> (this=0x0)
    at sourcepawn/compiler/parse-node.h:136
#3  0x56711274 in sp::cc::MethodmapDecl::LookupMethodmap (decl=0x0)
    at sourcepawn/compiler/parse-node.cpp:194
#4  0x566fe15a in sp::cc::MethodmapDecl::Bind (this=0x56a2dbb8, sc=...)
    at sourcepawn/compiler/name-resolution.cpp:1142
```

https://github.com/alliedmodders/sourcepawn/blob/35e55c8486b30e67f95145c680fe0942d4de8aa2/compiler/name-resolution.cpp#L1141-L1144

Probably just need to check `parent` here before using it?

**Comment by dvander** [comment]
Thanks, this has been fixed on master.
