### ISSUE TITLE
Docgen choking on SM topmenus.inc

### ISSUE THREAD

**Issue by psychonic** [alliedmodders/sourcepawn#227]
Specifically https://github.com/alliedmodders/sourcemod/blob/74512575/plugins/include/topmenus.inc

I've not had luck in narrowing this down further. Output of generate.py is just:
```
Failed to process ../../../../sourcemod/plugins/include/topmenus.inc:

Traceback (most recent call last):
  File "generate.py", line 624, in <module>
    main()
  File "generate.py", line 601, in main
    gen.generate()
  File "generate.py", line 189, in generate
    self.parse_include(include)
  File "generate.py", line 208, in parse_include
    raise Exception('failed to parse file')
Exception: failed to parse file
```

**Comment by psychonic** [comment]
I believe this is where it's going haywire.

```
Program received signal SIGSEGV, Segmentation fault.
sp::Type::isWrapped() const () at /groups/sourcemod/scripts/sourcepawn/exp/compiler/types.h:398
398         return canonical_ != this;
(gdb) bt
#0  sp::Type::isWrapped() const () at /groups/sourcemod/scripts/sourcepawn/exp/compiler/types.h:398
#1  0x08055caa in sp::Type::canonical() () at /groups/sourcemod/scripts/sourcepawn/exp/compiler/types.h:406
#2  0x08055c47 in sp::Type::isReference() () at /groups/sourcemod/scripts/sourcepawn/exp/compiler/types.h:379
#3  0x08065ada in BuildTypeFromSignature(sp::ast::FunctionSignature const*, sp::TypeDiagFlags) () at /groups/sourcemod/scripts/sourcepawn/exp/compiler/types.cpp:300
#4  0x080647ee in BuildTypeFromSpecifier(sp::ast::TypeSpecifier const*, sp::Atom*, sp::TypeDiagFlags) ()
    at /groups/sourcemod/scripts/sourcepawn/exp/compiler/types.cpp:339
#5  0x0806443b in sp::BuildTypeName(sp::ast::TypeSpecifier const*, sp::Atom*, sp::TypeDiagFlags) () at /groups/sourcemod/scripts/sourcepawn/exp/compiler/types.cpp:390
#6  0x08055569 in Analyzer::toJson(sp::ast::TypeSpecifier const*, sp::Atom*) () at /groups/sourcemod/scripts/sourcepawn/exp/tools/docparse/docparse.cpp:323
#7  0x08053cb3 in Analyzer::toJson(sp::ast::TypeExpr const&, sp::Atom*) () at /groups/sourcemod/scripts/sourcepawn/exp/tools/docparse/docparse.cpp:331
#8  0x08051c4b in Analyzer::visitTypedefDecl(sp::ast::TypedefDecl*) () at /groups/sourcemod/scripts/sourcepawn/exp/tools/docparse/docparse.cpp:250
#9  0x08089187 in sp::ast::TypedefDecl::accept(sp::ast::AstVisitor*) () at /groups/sourcemod/scripts/sourcepawn/exp/compiler/parser/ast.h:1820
#10 0x0804f799 in Analyzer::analyze(sp::ast::ParseTree*) () at /groups/sourcemod/scripts/sourcepawn/exp/tools/docparse/docparse.cpp:174
#11 0x080495cd in Run(sp::CompileContext&, char const*) () at /groups/sourcemod/scripts/sourcepawn/exp/tools/docparse/docparse.cpp:448
#12 0x080491ec in main () at /groups/sourcemod/scripts/sourcepawn/exp/tools/docparse/docparse.cpp:477
```

**Comment by dvander** [comment]
Thanks, this code is gross. Normally type specifiers are converted to types, but docgen skips that step so it can parse files without type checking. So all the pretty-printing code has to check both pointers.
